app:
  name: kratos-im:jobs-service
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    brokers:
      - 127.0.0.1:9092
  mongo:
    url: mongodb://root:123456@127.0.0.1:27017
    db: kratos-im
  ws:
    host: 127.0.0.1:10090
    patten: /ws
msg_read_handler:
  # 群消息合并配置
  group_msg_merge: true # 是否开启消息合并
  group_msg_merge_interval: 60 # 消息合并时间间隔(秒)
  group_msg_merge_max_size: 10 # 最大消息合并数量