// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-im/app/im/internal/biz"
	"kratos-im/app/im/internal/conf"
	"kratos-im/app/im/internal/data"
	"kratos-im/app/im/internal/server"
	"kratos-im/app/im/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, app *conf.App, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	database, err := data.NewMongo(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, logger, database)
	if err != nil {
		return nil, nil, err
	}
	imRepo := data.NewIMRepo(dataData, logger)
	imUsecase := biz.NewIMUsecase(imRepo, logger)
	broker := data.NewMQClient(confData, logger)
	imService := service.NewIMService(imUsecase, broker)
	rwsServer := server.NewWebsocketServer(confServer, auth, logger, imService)
	grpcServer := server.NewGRPCServer(confServer, imService, logger)
	registrar := data.NewRegistrar(registry)
	kratosApp := newApp(logger, rwsServer, grpcServer, registrar, app)
	return kratosApp, func() {
		cleanup()
	}, nil
}
