server:
  http:
    addr: 0.0.0.0:10010
    timeout: 1s
  grpc:
    addr: 0.0.0.0:10009
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/kratos-im?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    password: ""
    db: 0
auth:
  key: secret!@#123
  expire: 604800
oauth2:
  # github oauth2
  github:
    client_id: yourclientid
    client_secret: yourclientsecret
    redirect_url: http://localhost:8080/oauth2/github/callback