// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-im/app/jobs/internal/biz"
	"kratos-im/app/jobs/internal/conf"
	"kratos-im/app/jobs/internal/data"
	"kratos-im/app/jobs/internal/server"
	"kratos-im/app/jobs/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, app *conf.App, registry *conf.Registry, discovery *conf.Discovery, logger log.Logger) (*kratos.App, func(), error) {
	cmdable := data.NewRedis(confData, logger)
	client, err := data.NewMongo(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	iClient, err := data.NewWsClient(confData, logger, cmdable)
	if err != nil {
		return nil, nil, err
	}
	registryDiscovery := data.NewDiscovery(registry)
	socialClient := data.NewSocialServiceClient(discovery, registryDiscovery)
	dataData, cleanup, err := data.NewData(confData, logger, cmdable, client, iClient, socialClient)
	if err != nil {
		return nil, nil, err
	}
	consumerRepo := data.NewConsumerRepo(dataData, logger)
	consumerUsecase := biz.NewConsumerUsecase(consumerRepo, logger, iClient)
	consumerService := service.NewConsumerService(consumerUsecase)
	kafkaServer := server.NewKafkaServer(confData, logger, consumerService)
	registrar := data.NewRegistrar(registry)
	kratosApp := newApp(logger, kafkaServer, app, registrar)
	return kratosApp, func() {
		cleanup()
	}, nil
}
