app:
  name: kratos-im:social-service
server:
  http:
    addr: 0.0.0.0:10012
    timeout: 1s
  grpc:
    addr: 0.0.0.0:10011
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/kratos-im?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  key: tkP2yq!i=oamTR#oQ:8n
  expire: 604800