// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v5.26.0
// source: gateway/gateway.proto

package gateway

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGatewayFriendList = "/api.gateway.Gateway/FriendList"
const OperationGatewayFriendPutIn = "/api.gateway.Gateway/FriendPutIn"
const OperationGatewayFriendPutInHandle = "/api.gateway.Gateway/FriendPutInHandle"
const OperationGatewayFriendPutInList = "/api.gateway.Gateway/FriendPutInList"
const OperationGatewayFriendsOnline = "/api.gateway.Gateway/FriendsOnline"
const OperationGatewayGetChatLog = "/api.gateway.Gateway/GetChatLog"
const OperationGatewayGetConversations = "/api.gateway.Gateway/GetConversations"
const OperationGatewayGetReadChatRecords = "/api.gateway.Gateway/GetReadChatRecords"
const OperationGatewayGroupCreate = "/api.gateway.Gateway/GroupCreate"
const OperationGatewayGroupList = "/api.gateway.Gateway/GroupList"
const OperationGatewayGroupMembersOnline = "/api.gateway.Gateway/GroupMembersOnline"
const OperationGatewayGroupPutInHandle = "/api.gateway.Gateway/GroupPutInHandle"
const OperationGatewayGroupPutin = "/api.gateway.Gateway/GroupPutin"
const OperationGatewayGroupPutinList = "/api.gateway.Gateway/GroupPutinList"
const OperationGatewayGroupUsers = "/api.gateway.Gateway/GroupUsers"
const OperationGatewayPutConversations = "/api.gateway.Gateway/PutConversations"
const OperationGatewaySetUpUserConversation = "/api.gateway.Gateway/SetUpUserConversation"
const OperationGatewayUserLogin = "/api.gateway.Gateway/UserLogin"

type GatewayHTTPServer interface {
	// FriendList 好友列表
	FriendList(context.Context, *FriendListReq) (*FriendListResp, error)
	// FriendPutIn 好友申请
	FriendPutIn(context.Context, *FriendPutInReq) (*FriendPutInResp, error)
	// FriendPutInHandle 好友申请处理
	FriendPutInHandle(context.Context, *FriendPutInHandleReq) (*FriendPutInHandleResp, error)
	// FriendPutInList 好友申请列表
	FriendPutInList(context.Context, *FriendPutInListReq) (*FriendPutInListResp, error)
	// FriendsOnline 在线好友情况
	FriendsOnline(context.Context, *FriendsOnlineReq) (*FriendsOnlineResp, error)
	// GetChatLog 获取聊天记录
	GetChatLog(context.Context, *GetChatLogReq) (*GetChatLogResp, error)
	// GetConversations 获取会话列表
	GetConversations(context.Context, *GetConversationsReq) (*GetConversationsResp, error)
	// GetReadChatRecords 获取消息已读记录
	GetReadChatRecords(context.Context, *GetReadChatRecordsReq) (*GetReadChatRecordsResp, error)
	// GroupCreate 创建群
	GroupCreate(context.Context, *GroupCreateReq) (*GroupCreateResp, error)
	// GroupList 群列表
	GroupList(context.Context, *GroupListReq) (*GroupListResp, error)
	// GroupMembersOnline 在线群成员情况
	GroupMembersOnline(context.Context, *GroupMembersOnlineReq) (*GroupMembersOnlineResp, error)
	// GroupPutInHandle 入群申请处理
	GroupPutInHandle(context.Context, *GroupPutInHandleReq) (*GroupPutInHandleResp, error)
	// GroupPutin 入群申请
	GroupPutin(context.Context, *GroupPutinReq) (*GroupPutinResp, error)
	// GroupPutinList 入群申请列表
	GroupPutinList(context.Context, *GroupPutinListReq) (*GroupPutinListResp, error)
	// GroupUsers 群成员列表
	GroupUsers(context.Context, *GroupUsersReq) (*GroupUsersResp, error)
	// PutConversations 更新会话
	PutConversations(context.Context, *PutConversationsReq) (*PutConversationsResp, error)
	// SetUpUserConversation 建立会话
	SetUpUserConversation(context.Context, *SetUpUserConversationReq) (*SetUpUserConversationResp, error)
	// UserLogin 用户登录
	UserLogin(context.Context, *UserLoginReq) (*UserLoginResp, error)
}

func RegisterGatewayHTTPServer(s *http.Server, srv GatewayHTTPServer) {
	r := s.Route("/")
	r.POST("/group/create", _Gateway_GroupCreate0_HTTP_Handler(srv))
	r.PUT("/group/putin", _Gateway_GroupPutin0_HTTP_Handler(srv))
	r.GET("/group/putin/list", _Gateway_GroupPutinList0_HTTP_Handler(srv))
	r.PUT("/group/putin/handle", _Gateway_GroupPutInHandle0_HTTP_Handler(srv))
	r.GET("/group/list", _Gateway_GroupList0_HTTP_Handler(srv))
	r.GET("/group/users", _Gateway_GroupUsers0_HTTP_Handler(srv))
	r.PUT("/friend/putin", _Gateway_FriendPutIn0_HTTP_Handler(srv))
	r.PUT("/friend/putin/handle", _Gateway_FriendPutInHandle0_HTTP_Handler(srv))
	r.GET("/friend/putin/list", _Gateway_FriendPutInList0_HTTP_Handler(srv))
	r.GET("/friend/list", _Gateway_FriendList0_HTTP_Handler(srv))
	r.GET("/friend/online", _Gateway_FriendsOnline0_HTTP_Handler(srv))
	r.GET("/group/online", _Gateway_GroupMembersOnline0_HTTP_Handler(srv))
	r.POST("/conversation/setup", _Gateway_SetUpUserConversation0_HTTP_Handler(srv))
	r.GET("/conversation/list", _Gateway_GetConversations0_HTTP_Handler(srv))
	r.PUT("/conversation/update", _Gateway_PutConversations0_HTTP_Handler(srv))
	r.GET("/chat-log/list", _Gateway_GetChatLog0_HTTP_Handler(srv))
	r.GET("/read-chat-records/list", _Gateway_GetReadChatRecords0_HTTP_Handler(srv))
	r.POST("/user/login", _Gateway_UserLogin0_HTTP_Handler(srv))
}

func _Gateway_GroupCreate0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GroupCreateReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGroupCreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GroupCreate(ctx, req.(*GroupCreateReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupCreateResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_GroupPutin0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GroupPutinReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGroupPutin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GroupPutin(ctx, req.(*GroupPutinReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupPutinResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_GroupPutinList0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GroupPutinListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGroupPutinList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GroupPutinList(ctx, req.(*GroupPutinListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupPutinListResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_GroupPutInHandle0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GroupPutInHandleReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGroupPutInHandle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GroupPutInHandle(ctx, req.(*GroupPutInHandleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupPutInHandleResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_GroupList0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GroupListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGroupList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GroupList(ctx, req.(*GroupListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupListResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_GroupUsers0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GroupUsersReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGroupUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GroupUsers(ctx, req.(*GroupUsersReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupUsersResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_FriendPutIn0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FriendPutInReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayFriendPutIn)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FriendPutIn(ctx, req.(*FriendPutInReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FriendPutInResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_FriendPutInHandle0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FriendPutInHandleReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayFriendPutInHandle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FriendPutInHandle(ctx, req.(*FriendPutInHandleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FriendPutInHandleResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_FriendPutInList0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FriendPutInListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayFriendPutInList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FriendPutInList(ctx, req.(*FriendPutInListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FriendPutInListResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_FriendList0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FriendListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayFriendList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FriendList(ctx, req.(*FriendListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FriendListResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_FriendsOnline0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FriendsOnlineReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayFriendsOnline)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FriendsOnline(ctx, req.(*FriendsOnlineReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FriendsOnlineResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_GroupMembersOnline0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GroupMembersOnlineReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGroupMembersOnline)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GroupMembersOnline(ctx, req.(*GroupMembersOnlineReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupMembersOnlineResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_SetUpUserConversation0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetUpUserConversationReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewaySetUpUserConversation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetUpUserConversation(ctx, req.(*SetUpUserConversationReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetUpUserConversationResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_GetConversations0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetConversationsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGetConversations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConversations(ctx, req.(*GetConversationsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetConversationsResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_PutConversations0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PutConversationsReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayPutConversations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PutConversations(ctx, req.(*PutConversationsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PutConversationsResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_GetChatLog0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetChatLogReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGetChatLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChatLog(ctx, req.(*GetChatLogReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetChatLogResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_GetReadChatRecords0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReadChatRecordsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGetReadChatRecords)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReadChatRecords(ctx, req.(*GetReadChatRecordsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReadChatRecordsResp)
		return ctx.Result(200, reply)
	}
}

func _Gateway_UserLogin0_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserLoginReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayUserLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UserLogin(ctx, req.(*UserLoginReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserLoginResp)
		return ctx.Result(200, reply)
	}
}

type GatewayHTTPClient interface {
	FriendList(ctx context.Context, req *FriendListReq, opts ...http.CallOption) (rsp *FriendListResp, err error)
	FriendPutIn(ctx context.Context, req *FriendPutInReq, opts ...http.CallOption) (rsp *FriendPutInResp, err error)
	FriendPutInHandle(ctx context.Context, req *FriendPutInHandleReq, opts ...http.CallOption) (rsp *FriendPutInHandleResp, err error)
	FriendPutInList(ctx context.Context, req *FriendPutInListReq, opts ...http.CallOption) (rsp *FriendPutInListResp, err error)
	FriendsOnline(ctx context.Context, req *FriendsOnlineReq, opts ...http.CallOption) (rsp *FriendsOnlineResp, err error)
	GetChatLog(ctx context.Context, req *GetChatLogReq, opts ...http.CallOption) (rsp *GetChatLogResp, err error)
	GetConversations(ctx context.Context, req *GetConversationsReq, opts ...http.CallOption) (rsp *GetConversationsResp, err error)
	GetReadChatRecords(ctx context.Context, req *GetReadChatRecordsReq, opts ...http.CallOption) (rsp *GetReadChatRecordsResp, err error)
	GroupCreate(ctx context.Context, req *GroupCreateReq, opts ...http.CallOption) (rsp *GroupCreateResp, err error)
	GroupList(ctx context.Context, req *GroupListReq, opts ...http.CallOption) (rsp *GroupListResp, err error)
	GroupMembersOnline(ctx context.Context, req *GroupMembersOnlineReq, opts ...http.CallOption) (rsp *GroupMembersOnlineResp, err error)
	GroupPutInHandle(ctx context.Context, req *GroupPutInHandleReq, opts ...http.CallOption) (rsp *GroupPutInHandleResp, err error)
	GroupPutin(ctx context.Context, req *GroupPutinReq, opts ...http.CallOption) (rsp *GroupPutinResp, err error)
	GroupPutinList(ctx context.Context, req *GroupPutinListReq, opts ...http.CallOption) (rsp *GroupPutinListResp, err error)
	GroupUsers(ctx context.Context, req *GroupUsersReq, opts ...http.CallOption) (rsp *GroupUsersResp, err error)
	PutConversations(ctx context.Context, req *PutConversationsReq, opts ...http.CallOption) (rsp *PutConversationsResp, err error)
	SetUpUserConversation(ctx context.Context, req *SetUpUserConversationReq, opts ...http.CallOption) (rsp *SetUpUserConversationResp, err error)
	UserLogin(ctx context.Context, req *UserLoginReq, opts ...http.CallOption) (rsp *UserLoginResp, err error)
}

type GatewayHTTPClientImpl struct {
	cc *http.Client
}

func NewGatewayHTTPClient(client *http.Client) GatewayHTTPClient {
	return &GatewayHTTPClientImpl{client}
}

func (c *GatewayHTTPClientImpl) FriendList(ctx context.Context, in *FriendListReq, opts ...http.CallOption) (*FriendListResp, error) {
	var out FriendListResp
	pattern := "/friend/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayFriendList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) FriendPutIn(ctx context.Context, in *FriendPutInReq, opts ...http.CallOption) (*FriendPutInResp, error) {
	var out FriendPutInResp
	pattern := "/friend/putin"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayFriendPutIn))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) FriendPutInHandle(ctx context.Context, in *FriendPutInHandleReq, opts ...http.CallOption) (*FriendPutInHandleResp, error) {
	var out FriendPutInHandleResp
	pattern := "/friend/putin/handle"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayFriendPutInHandle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) FriendPutInList(ctx context.Context, in *FriendPutInListReq, opts ...http.CallOption) (*FriendPutInListResp, error) {
	var out FriendPutInListResp
	pattern := "/friend/putin/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayFriendPutInList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) FriendsOnline(ctx context.Context, in *FriendsOnlineReq, opts ...http.CallOption) (*FriendsOnlineResp, error) {
	var out FriendsOnlineResp
	pattern := "/friend/online"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayFriendsOnline))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GetChatLog(ctx context.Context, in *GetChatLogReq, opts ...http.CallOption) (*GetChatLogResp, error) {
	var out GetChatLogResp
	pattern := "/chat-log/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayGetChatLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GetConversations(ctx context.Context, in *GetConversationsReq, opts ...http.CallOption) (*GetConversationsResp, error) {
	var out GetConversationsResp
	pattern := "/conversation/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayGetConversations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GetReadChatRecords(ctx context.Context, in *GetReadChatRecordsReq, opts ...http.CallOption) (*GetReadChatRecordsResp, error) {
	var out GetReadChatRecordsResp
	pattern := "/read-chat-records/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayGetReadChatRecords))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GroupCreate(ctx context.Context, in *GroupCreateReq, opts ...http.CallOption) (*GroupCreateResp, error) {
	var out GroupCreateResp
	pattern := "/group/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayGroupCreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GroupList(ctx context.Context, in *GroupListReq, opts ...http.CallOption) (*GroupListResp, error) {
	var out GroupListResp
	pattern := "/group/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayGroupList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GroupMembersOnline(ctx context.Context, in *GroupMembersOnlineReq, opts ...http.CallOption) (*GroupMembersOnlineResp, error) {
	var out GroupMembersOnlineResp
	pattern := "/group/online"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayGroupMembersOnline))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GroupPutInHandle(ctx context.Context, in *GroupPutInHandleReq, opts ...http.CallOption) (*GroupPutInHandleResp, error) {
	var out GroupPutInHandleResp
	pattern := "/group/putin/handle"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayGroupPutInHandle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GroupPutin(ctx context.Context, in *GroupPutinReq, opts ...http.CallOption) (*GroupPutinResp, error) {
	var out GroupPutinResp
	pattern := "/group/putin"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayGroupPutin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GroupPutinList(ctx context.Context, in *GroupPutinListReq, opts ...http.CallOption) (*GroupPutinListResp, error) {
	var out GroupPutinListResp
	pattern := "/group/putin/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayGroupPutinList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GroupUsers(ctx context.Context, in *GroupUsersReq, opts ...http.CallOption) (*GroupUsersResp, error) {
	var out GroupUsersResp
	pattern := "/group/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayGroupUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) PutConversations(ctx context.Context, in *PutConversationsReq, opts ...http.CallOption) (*PutConversationsResp, error) {
	var out PutConversationsResp
	pattern := "/conversation/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayPutConversations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) SetUpUserConversation(ctx context.Context, in *SetUpUserConversationReq, opts ...http.CallOption) (*SetUpUserConversationResp, error) {
	var out SetUpUserConversationResp
	pattern := "/conversation/setup"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewaySetUpUserConversation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) UserLogin(ctx context.Context, in *UserLoginReq, opts ...http.CallOption) (*UserLoginResp, error) {
	var out UserLoginResp
	pattern := "/user/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayUserLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
